### ISSUE TITLE
Instructions on usage

### ISSUE THREAD

**Issue by Realswitzer** [DynamicCake/BlookPanel#1]
Maybe adding a section on how to use it to the README may be helpful. Granted, if I knew I would have probably made a PR, but in any case, it would make the project more “accessible”, if that’s the right term (allows more people to use it).

**Comment by DynamicCake** [comment]
Sure, Il add it on release, also there will be a version that works out of the box

**Comment by DynamicCake** [comment]
Instructions are finished, thank you for contributing!
